name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      confirm:
        description: 'Type "destroy" to confirm'
        required: true
        type: string

env:
  TF_VERSION: '1.5.0'
  AWS_REGION: 'us-east-1'

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    defaults:
      run:
        working-directory: ./environments/${{ github.event.inputs.environment }}

    steps:
    - name: Validate Confirmation
      run: |
        if [ "${{ github.event.inputs.confirm }}" != "destroy" ]; then
          echo "❌ Confirmation failed. You must type 'destroy' to confirm."
          exit 1
        fi
        echo "✅ Confirmation validated."

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init
      env:
        TF_VAR_key_name: ${{ secrets.AWS_KEY_PAIR_NAME }}

    - name: Terraform Plan Destroy
      run: terraform plan -destroy -out=destroy-plan
      env:
        TF_VAR_key_name: ${{ secrets.AWS_KEY_PAIR_NAME }}
        TF_VAR_allowed_cidr_blocks: '["${{ secrets.ALLOWED_CIDR }}"]'

    - name: Terraform Destroy
      run: terraform apply -auto-approve destroy-plan
      env:
        TF_VAR_key_name: ${{ secrets.AWS_KEY_PAIR_NAME }}
        TF_VAR_allowed_cidr_blocks: '["${{ secrets.ALLOWED_CIDR }}"]'